# Global settings applied to the whole site.  
# “base” is directory to change to before starting build, and
# “public” is the directory to publish (relative to root of your repo).
# “command” is your build command.

[build]
  publish = "public/"
  command = "gatsby build"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "gatsby build"
  [context.production.environment]
    NODE_VERSION = "6.11.0"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview.environment]

# Branch Deploy context: All deploys that are not in
# an active Deploy Preview will inherit these settings.
[context.branch-deploy]

# Specific branch context: Deploys from this branch
# will take these settings and override their
# current ones.
[context.feature]

[context."features/branch"]
  command = "gulp"
